Internal Server Error: /directory/forgot-password/
Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\member_dir_backend\directory\views.py", line 101, in forgot_password
    PasswordResetOTP.objects.filter(
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'admin_account' into field. Choices are: account_id, account_id_id, created_at, expires_at, id, is_used, otp_code
"POST /directory/forgot-password/ HTTP/1.1" 500 153830
Internal Server Error: /directory/forgot-password/
Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\member_dir_backend\directory\views.py", line 101, in forgot_password
    PasswordResetOTP.objects.filter(
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'admin_account' into field. Choices are: account_id, account_id_id, created_at, expires_at, id, is_used, otp_code
"POST /directory/forgot-password/ HTTP/1.1" 500 152826
Internal Server Error: /directory/forgot-password/
Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column directory_passwordresetotp.admin_account_id does not exist
LINE 1: DELETE FROM "directory_passwordresetotp" WHERE ("directory_p...
                                                        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\member_dir_backend\directory\views.py", line 104, in forgot_password
    ).delete()
      ^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1199, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\deletion.py", line 467, in delete
    count = qs._raw_delete(using=self.using)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1221, in _raw_delete
    return query.get_compiler(using).execute_sql(ROW_COUNT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column directory_passwordresetotp.admin_account_id does not exist
LINE 1: DELETE FROM "directory_passwordresetotp" WHERE ("directory_p...
                                                        ^

"POST /directory/forgot-password/ HTTP/1.1" 500 162389
Internal Server Error: /directory/forgot-password/
Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column directory_passwordresetotp.account_id does not exist
LINE 1: DELETE FROM "directory_passwordresetotp" WHERE ("directory_p...
                                                        ^
HINT:  Perhaps you meant to reference the column "directory_passwordresetotp.account_id_id".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\member_dir_backend\directory\views.py", line 104, in forgot_password
    ).delete()
      ^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1199, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\deletion.py", line 467, in delete
    count = qs._raw_delete(using=self.using)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1221, in _raw_delete
    return query.get_compiler(using).execute_sql(ROW_COUNT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column directory_passwordresetotp.account_id does not exist
LINE 1: DELETE FROM "directory_passwordresetotp" WHERE ("directory_p...
                                                        ^
HINT:  Perhaps you meant to reference the column "directory_passwordresetotp.account_id_id".

"POST /directory/forgot-password/ HTTP/1.1" 500 163698
Internal Server Error: /directory/forgot-password/
Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column directory_passwordresetotp.account_id does not exist
LINE 1: DELETE FROM "directory_passwordresetotp" WHERE ("directory_p...
                                                        ^
HINT:  Perhaps you meant to reference the column "directory_passwordresetotp.account_id_id".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\member_dir_backend\directory\views.py", line 104, in forgot_password
    ).delete()
      ^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1199, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\deletion.py", line 467, in delete
    count = qs._raw_delete(using=self.using)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\query.py", line 1221, in _raw_delete
    return query.get_compiler(using).execute_sql(ROW_COUNT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column directory_passwordresetotp.account_id does not exist
LINE 1: DELETE FROM "directory_passwordresetotp" WHERE ("directory_p...
                                                        ^
HINT:  Perhaps you meant to reference the column "directory_passwordresetotp.account_id_id".

"POST /directory/forgot-password/ HTTP/1.1" 500 163698
Internal Server Error: /directory/verify-otp/
Traceback (most recent call last):
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\member_dir_backend\directory\views.py", line 150, in verify_otp
    if otp_record.is_expired():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Austin\Desktop\School Files\OJT\FFWPU-Member-Diretory\member_dir_backend\directory\models.py", line 55, in is_expired
    return datetime.now() > self.expires_at
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
"POST /directory/verify-otp/ HTTP/1.1" 500 110998
